### ISSUE TITLE
Node.js SDK 中创建租户时，`logo` 和 `description` 参数与文档描述不一致

### ISSUE THREAD

**Issue by Meeken1998** [Authing/docs#128]
# 反馈模版
## 问题分类

- [ ] 没找到想了解的信息
- [ ] 步骤说明不清晰/看不懂
- [x] 内容有错
- [ ] 其他

## 请具体描述你的问题

文档地址：
[创建租户](https://docs.authing.cn/v2/tenant/reference/sdk-for-node/management/TenantManagementClient.html#%E5%88%9B%E5%BB%BA%E7%A7%9F%E6%88%B7)

SDK 版本：

```json
    "authing-js-sdk": "^4.23.35"
```

在创建租户时，`logo` 和 `description` 参数在文档内为可选，实际开发体验时必选，若留空会报 400：参数错误

<img width="607" alt="image" src="https://user-images.githubusercontent.com/42825670/184595414-4e8fa3e0-480d-4593-948b-bc40feb24e89.png">

## 你期望的结果

1. 希望上述参数与文档一致
2. `tenant` 类下的大多数返回值是 `any`，内测阶段可以理解，预计什么时候能把类型支持一下呢

**Comment by liaochangjiang** [comment]
logo 参数不能传空字符串 `""` 

已对错误提示给出具体提示：

```
{ code: 400, message: 'logo must be an URL address' }
```
