### ISSUE TITLE
文档跳转错误：“SSO综述”跳转“如何创建第一个应用”

### ISSUE THREAD

**Issue by fengdasuk19** [Authing/docs#48]
## 问题分类

- [ ] 没找到想了解的信息
- [ ] 步骤说明不清晰/看不懂
- [x] 内容有错
- [ ] 其他

## 请具体描述你的问题

[单点登录 SSO 综述](https://docs.authing.cn/v2/guides/sso/)中提到：

> 如果你还没有创建过应用，可以了解[如何创建第一个应用](https://docs.authing.cn/v2/guides/sso/create-app.html)。

这里对“如何创建第一个应用”的引用出错了，点开是404。

## 你期望的结果

不知道实际应该跳到哪里，猜测是 https://docs.authing.cn/v2/guides/app/create-app.html

**Comment by willin** [comment]
please wait for deployment
