### ISSUE TITLE
Android拼错了😄

### ISSUE THREAD

**Issue by sanguinedab** [Authing/docs#55]
# 反馈模版
## 问题分类

- [ ] 没找到想了解的信息
- [ ] 步骤说明不清晰/看不懂
- [ ] 内容有错
- [ ] 其他

**Comment by sanguinedab** [comment]
https://docs.authing.cn/v2/guides/basics/platform-guide/integrate-with-mobile-app.html，标题里安卓拼错了Android

**Comment by erniu** [comment]
> [https://docs.authing.cn/v2/guides/basics/platform-guide/integrate-with-mobile-app.html，标题里安卓拼错了Android](https://docs.authing.cn/v2/guides/basics/platform-guide/integrate-with-mobile-app.html%EF%BC%8C%E6%A0%87%E9%A2%98%E9%87%8C%E5%AE%89%E5%8D%93%E6%8B%BC%E9%94%99%E4%BA%86Android)

已修复，下次发版就生效了
